### ISSUE TITLE
Peer-peer Code review -week1,December 1st

### ISSUE THREAD

**Issue by collins-kiprotich** [lawrahkonwea/Capstone-project-MODULE1#2]
### @lawrahkonwea, Your websites looks great. You really did a great job! 🏆 

I found three issues and suggestions to improve your project;

- On your mobile menu, add a link to home so the use can navigate back to the main menu
- In your partners section, replace  the logo images to png format
- Kindly replace your logo image to an actual logo

Well done!!! 👍 you rocked it

**Comment by annaeliana7** [comment]
Images of Issues found: 

1. 
<img width="390" alt="1  mobile version-menu" src="https://user-images.githubusercontent.com/112557951/204994986-091cbe91-01dd-4889-8858-c16cc95d8103.png">

2. 
<img width="791" alt="2  Partners- png format on the images" src="https://user-images.githubusercontent.com/112557951/204995035-723314d2-c5a3-4234-a7da-0b33a49cda6a.png">

3. 
<img width="194" alt="3  Logo" src="https://user-images.githubusercontent.com/112557951/204995063-776ce819-b226-4ab4-96fa-50882bb0b063.png">
